export const dddToStateMap = {
  '68': 'Acre',
  '82': 'Alagoas',
  '96': 'Amapá',
  '92': 'Amazonas',
  '97': 'Amazonas',
  '71': 'Bahia',
  '73': 'Bahia',
  '74': 'Bahia',
  '75': 'Bahia',
  '77': 'Bahia',
  '85': 'Ceará',
  '88': 'Ceará',
  '61': 'Distrito Federal',
  '27': 'Espírito Santo',
  '28': 'Espírito Santo',
  '62': 'Goiás',
  '64': 'Goiás',
  '98': 'Maranhão',
  '99': 'Maranhão',
  '65': 'Mato Grosso',
  '66': 'Mato Grosso',
  '67': 'Mato Grosso do Sul',
  '31': 'Minas Gerais',
  '32': 'Minas Gerais',
  '33': 'Minas Gerais',
  '34': 'Minas Gerais',
  '35': 'Minas Gerais',
  '37': 'Minas Gerais',
  '38': 'Minas Gerais',
  '91': 'Pará',
  '93': 'Pará',
  '94': 'Pará',
  '83': 'Paraíba',
  '41': 'Paraná',
  '42': 'Paraná',
  '43': 'Paraná',
  '44': 'Paraná',
  '45': 'Paraná',
  '46': 'Paraná',
  '81': 'Pernambuco',
  '87': 'Pernambuco',
  '86': 'Piauí',
  '89': 'Piauí',
  '21': 'Rio de Janeiro',
  '22': 'Rio de Janeiro',
  '24': 'Rio de Janeiro',
  '84': 'Rio Grande do Norte',
  '51': 'Rio Grande do Sul',
  '53': 'Rio Grande do Sul',
  '54': 'Rio Grande do Sul',
  '55': 'Rio Grande do Sul',
  '69': 'Rondônia',
  '95': 'Roraima',
  '47': 'Santa Catarina',
  '48': 'Santa Catarina',
  '49': 'Santa Catarina',
  '11': 'São Paulo',
  '12': 'São Paulo',
  '13': 'São Paulo',
  '14': 'São Paulo',
  '15': 'São Paulo',
  '16': 'São Paulo',
  '17': 'São Paulo',
  '18': 'São Paulo',
  '19': 'São Paulo',
  '79': 'Sergipe',
  '63': 'Tocantins',
};
